<?php

/**
 * Implements hook_init().
 */
function livereload_init() {
  global $base_url;

  if (user_access('use livereload') && variable_get('livereload_js', TRUE)) {
    $path = 'http://';
    $path .= check_plain(variable_get('livereload_host', parse_url($base_url, PHP_URL_HOST)));
    $path .= ':' . check_plain(variable_get('livereload_port', 35729));
    $path .= '/livereload.js?snipver=1';
    drupal_add_js($path, 'external');
  }
}

/**
 * Implements hook_permission().
 */
function livereload_permission() {
  return array(
    'use livereload' => array(
      'title' => t('Use LiveReload'),
      'description' => t('Adds the livereload.js if it is enabled.'),
    ),
  );
}

/**
 * Implements hook_css_alter().
 *
 * Force CSS to be added with link tags, rather than @import.
 */
function livereload_css_alter(&$css) {
  if (user_access('use livereload') && variable_get('livereload_css', FALSE)) {
    foreach ($css as $key => $value) {
      $css[$key]['preprocess'] = FALSE;
    }
  }
}

/**
 * Implements hook_form_formID_alter().
 *
 * Add the possibility to en- and disable the livereload.js.
 */
function livereload_form_system_performance_settings_alter(&$form, &$form_state, $form_id) {
  global $base_url;

  $form['livereload'] = array(
    '#type' => 'fieldset',
    '#title' => 'LiveReload',
  );

  $form['livereload']['livereload_js'] = array(
    '#type' => 'checkbox',
    '#title' => t('Add livereload.js. <em>Note: this will only work if css aggregation is disabled.</em>'),
    '#default_value' => variable_get('livereload_js', 1),
    '#disabled' => FALSE,
  );

  $form['livereload']['livereload_css'] = array(
    '#type' => 'checkbox',
    '#title' => t('Force CSS to be added with link tags, rather than @import. <em>Note: if this option is enabled, the "%aggregate_css" functionallity of Drupal will not work.</em>', array('%aggregate_css' => t('Aggregate and compress CSS files.'))),
    '#default_value' => variable_get('livereload_css', 0),
    '#states' => array(
      'disabled' => array(
        ':input[name=preprocess_css]' => array('checked' => TRUE),
      ),
      'checked' => array(
        ':input[name=preprocess_css]' => array('checked' => FALSE),
      ),
    ),
  );

  $form['livereload']['livereload_host'] = array(
    '#type' => 'textfield',
    '#title' => t('Host'),
    '#description' => t('Host to connect to. Defaults to your current hostname. Do not include the protocol (i.e. http://)'),
    '#size' => 40,
    '#maxlength' => 255,
    '#default_value' => variable_get('livereload_host', parse_url($base_url, PHP_URL_HOST)),
  );

  $form['livereload']['livereload_port'] = array(
    '#type' => 'textfield',
    '#title' => t('Port'),
    '#size' => 8,
    '#maxlength' => 7,
    '#default_value' => variable_get('livereload_port', 35729),
  );


  $form['#validate'][] = 'livereload_system_performance_form_validate';
}

/**
 * Validation function for enabling livereload
 */
function livereload_system_performance_form_validate(&$form, &$form_state) {
  $values = $form_state['values'];

  if ($values['preprocess_css'] and $values['livereload_js']) {
    form_set_error('livereload_js', t('Cannot enable LiveReload with CSS aggregation enabled. Turn off CSS aggregator to continue.'));
  }
}
